server:
  error:
    whitelabel:
      enabled: false
  port: 20000
  tomcat:
    accept-count: 100
    threads:
      max: 500
    max-connections: 20000
    uri-encoding: UTF-8
    remoteip:
      internal-proxies: ""
  forward-headers-strategy: none


spring:
  jpa:
    open-in-view: false
  application:
    name: product-composite

services:
  host:
    product-server: http://localhost:20001
    recommendation-server: http://localhost:20002
    review-server: http://localhost:20003
